### ISSUE TITLE
Is there any plan to support vc2017 15.9

### ISSUE THREAD

**Issue by hwliu11** [oneiric/vld#2]
I use VLD on VC 2017 v15.9,vld cant load symbols,display err msg "xxx.dll included in memory leak detection does not have any debugging symbols available"

**Comment by oneiric** [comment]
I forked the repo to support Visual Studio 2019.
If you want to VC 2017, can you try the previous build?
https://kinddragon.github.io/vld/

**Comment by hwliu11** [comment]
OK,I try the ver 2.5.1.Thks
